In [1]:
from IPython.display import display, Latex
import numpy as np

def get_matrix(n: int):  # returns a matrix that satisfies to the conditions from the task #11
    m = np.ones((n, n), np.float)
    for i in range(n):
        for j in range(n):
            if i == j:
                m[i, j] = i + 2
            elif i < j:
                m[i, j] = 2
    return m


def det(m):
    m = m.copy()
    if not m.all():
        return 0
    d = 1
    while len(m) > 1:  # each iteration slices matrix until its dim = 1
        l = 0
        for i in range(len(m)):
            if m[i, 0] != 0:  # looking for the first nonzero element in the column
                l = i         # l -- index of that element
                d *= m[l, 0]
                m[l] = np.array([x / m[l, 0] for x in m[l]])  # making first element in the row equal 1
                break
        for i in range(l + 1, len(m)):  # making other elements in the column zero
            if m[i, 0] != 0:
                d *= m[i, 0]
                m[i] = np.array([x - y * m[i, 0] for x, y in zip(m[i], m[l])])
        m = m[:, 1:]  # removing first column
        temp = []
        for i in range(len(m)):  # removing l-row
            if i != l:
                temp.append(m[i])
        m = np.array(temp)  # "sliced" matrix

    return d * float(m)


def gauss(m: np.ndarray, f: np.ndarray):  # Gauss method
    m = m.copy()
    f = f.copy()
    n = len(m)
    expd_m = []
    x = []  # list for unknowns
    for i in range(n):  # creating expanded matrix
        row = m[i].tolist()
        row.append(f[i])
        expd_m.append(row)
    expd_m = np.array(expd_m)
    l = 0
    for k in range(n):
        for i in range(k, n):
            if expd_m[i, k] != 0:  # looking for the first nonzero element in the column
                l = i         # l -- index of that element
                expd_m[l] = np.array([x / expd_m[l, k] for x in expd_m[l]])  # making first element in the row equal 1
                break
        for i in range(l + 1, n):  # making other elements in the column zero
            if expd_m[i, k] != 0:
                expd_m[i] = np.array([y - x / expd_m[i, k] for x, y in zip(expd_m[i], expd_m[l])])
    for i in range(n - 1, -1, -1):
        x.append(expd_m[i, -1] -  sum(expd_m[i, i + 1:n] * x))
    x.reverse()
    return x



def inverse(m):  # finding inverse matrix usig Gauss method
    m = m.copy()
    n = len(m)
    inv = []
    for i in range(n):
        f = np.zeros(n)
        f[i] = 1
        inv.append(gauss(m, f))
    return np.transpose(np.array(inv))


<hr/>
### Метод Гаусса. Схема единственного деления.
Матрица $A$ задаётся следующим образом:

$a_{ij}=\begin{cases}i+1,\:  &i=j\\ 1,\quad &i>j,\\ 2,\quad &i<j;\:\:i,j=1,\ldots,n.\end{cases}$

<b>С помощью метода Гаусса найти:</b>

а) Определитель произвольной матрицы

б) Обратную матрицую

<hr/>Определитель находим с помощью функции __det()__.

Ниже подсчитаем определитель для матриц первых 4 размерностей с помощью __det()__ и встроенной функции __linalg.det()__
<hr/>

In [2]:
n = 5
for j in range(1, n):
    matrix = get_matrix(j)
    print(f"\nn = {j}\n")
    print(f"Сама матрица:\n {matrix}")
    print(f"\nОпределитель получившийся у нас: {det(matrix)}")
    print(f"\nОпределитель с помощью  встроенной функции: {round(np.linalg.det(matrix), 5)}")



n = 1

Сама матрица:
 [[2.]]

Определитель получившийся у нас: 2.0

Определитель с помощью  встроенной функции: 2.0

n = 2

Сама матрица:
 [[2. 2.]
 [1. 3.]]

Определитель получившийся у нас: 4.0

Определитель с помощью  встроенной функции: 4.0

n = 3

Сама матрица:
 [[2. 2. 2.]
 [1. 3. 2.]
 [1. 1. 4.]]

Определитель получившийся у нас: 12.0

Определитель с помощью  встроенной функции: 12.0

n = 4

Сама матрица:
 [[2. 2. 2. 2.]
 [1. 3. 2. 2.]
 [1. 1. 4. 2.]
 [1. 1. 1. 5.]]

Определитель получившийся у нас: 48.0

Определитель с помощью  встроенной функции: 48.0


<hr/>Обратную матрицу находит функция __inverse()__.

Ниже подсчитаем обратную матрицу для матриц первых 4 размерностей с помощью __inverse()__ и встроенной функции
__linalg.inv()__<hr/>

In [3]:
n = 5
for j in range(1, n):
    matrix = get_matrix(j)
    print(f"\nn = {j}\n")
    print(f'"Наша" обратная матрица:\n {inverse(matrix)}')
    print(f"\nОбратная матрица с помощью  встроенной функции:\n {np.linalg.inv(matrix)}")


n = 1

"Наша" обратная матрица:
 [[0.5]]

Обратная матрица с помощью  встроенной функции:
 [[0.5]]

n = 2

"Наша" обратная матрица:
 [[ 0.75 -0.5 ]
 [-0.25  0.5 ]]

Обратная матрица с помощью  встроенной функции:
 [[ 0.75 -0.5 ]
 [-0.25  0.5 ]]

n = 3

"Наша" обратная матрица:
 [[ 0.83333333 -0.5        -0.16666667]
 [-0.16666667  0.5        -0.16666667]
 [-0.16666667 -0.          0.33333333]]

Обратная матрица с помощью  встроенной функции:
 [[ 0.83333333 -0.5        -0.16666667]
 [-0.16666667  0.5        -0.16666667]
 [-0.16666667  0.          0.33333333]]

n = 4

"Наша" обратная матрица:
 [[ 0.875      -0.5        -0.16666667 -0.08333333]
 [-0.125       0.5        -0.16666667 -0.08333333]
 [-0.125      -0.          0.33333333 -0.08333333]
 [-0.125      -0.         -0.          0.25      ]]

Обратная матрица с помощью  встроенной функции:
 [[ 0.875      -0.5        -0.16666667 -0.08333333]
 [-0.125       0.5        -0.16666667 -0.08333333]
 [-0.125       0.          0.33333333 -0.08